# Generated by Django 4.2.1 on 2023-07-21 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 18, 56, 34, 940023)),
        ),
    ]
