# Generated by Django 4.2.1 on 2023-07-18 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='todo',
            name='copmlete',
            field=models.BooleanField(default=datetime.datetime(2023, 7, 18, 19, 4, 10, 68721)),
        ),
    ]
