# Generated by Django 4.2.1 on 2023-07-18 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_remove_todo_created_at_alter_todo_copmlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='copmlete',
            field=models.BooleanField(default=datetime.datetime(2023, 7, 18, 19, 6, 34, 853285, tzinfo=datetime.timezone.utc)),
        ),
    ]
